version: '3.8'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'bridge'
    ports:
      - 8096:8096
    volumes:
      - ${PATH_CONFIG}:/config
      - ${PATH_CACHE}:/cache
      - ${PATH_MEDIA}:/media:ro
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://media.devsiam.com
    extra_hosts:
      - "host.docker.internal:host-gateway"